In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [6]:
## Define the vocab size
voc_size = 10000

In [10]:
## one hot representation for every word
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[5699, 6007, 9328, 5683],
 [5699, 6007, 9328, 8701],
 [5699, 9352, 9328, 7498],
 [8145, 9629, 4571, 4580, 5577],
 [8145, 9629, 4571, 4580, 5623],
 [3818, 5699, 8967, 9328, 9425],
 [3643, 2955, 1091, 4580]]

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 5699, 6007, 9328, 5683],
       [   0,    0,    0,    0, 5699, 6007, 9328, 8701],
       [   0,    0,    0,    0, 5699, 9352, 9328, 7498],
       [   0,    0,    0, 8145, 9629, 4571, 4580, 5577],
       [   0,    0,    0, 8145, 9629, 4571, 4580, 5623],
       [   0,    0,    0, 3818, 5699, 8967, 9328, 9425],
       [   0,    0,    0,    0, 3643, 2955, 1091, 4580]])

In [14]:
## feature representation
dim = 10

In [15]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile(optimizer='adam',metrics='mse')


In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 154ms/step


array([[[ 0.00356767, -0.02594563, -0.03413204, -0.00815475,
          0.03996015,  0.01622197,  0.02027507, -0.00918136,
         -0.03313998, -0.01074614],
        [ 0.00356767, -0.02594563, -0.03413204, -0.00815475,
          0.03996015,  0.01622197,  0.02027507, -0.00918136,
         -0.03313998, -0.01074614],
        [ 0.00356767, -0.02594563, -0.03413204, -0.00815475,
          0.03996015,  0.01622197,  0.02027507, -0.00918136,
         -0.03313998, -0.01074614],
        [ 0.00356767, -0.02594563, -0.03413204, -0.00815475,
          0.03996015,  0.01622197,  0.02027507, -0.00918136,
         -0.03313998, -0.01074614],
        [-0.03854503, -0.04668442,  0.01068868, -0.04538208,
         -0.02251787, -0.01364915, -0.01776264,  0.03452767,
         -0.03856841,  0.04281293],
        [-0.01409448,  0.00152295, -0.0401078 ,  0.02151066,
         -0.02573876,  0.03013865, -0.00471014, -0.01068258,
         -0.02545031,  0.00162345],
        [ 0.04024539, -0.03094944, -0.01136745,  0.0

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 47ms/step


array([[ 0.00356767, -0.02594563, -0.03413204, -0.00815475,  0.03996015,
         0.01622197,  0.02027507, -0.00918136, -0.03313998, -0.01074614],
       [ 0.00356767, -0.02594563, -0.03413204, -0.00815475,  0.03996015,
         0.01622197,  0.02027507, -0.00918136, -0.03313998, -0.01074614],
       [ 0.00356767, -0.02594563, -0.03413204, -0.00815475,  0.03996015,
         0.01622197,  0.02027507, -0.00918136, -0.03313998, -0.01074614],
       [ 0.00356767, -0.02594563, -0.03413204, -0.00815475,  0.03996015,
         0.01622197,  0.02027507, -0.00918136, -0.03313998, -0.01074614],
       [-0.03854503, -0.04668442,  0.01068868, -0.04538208, -0.02251787,
        -0.01364915, -0.01776264,  0.03452767, -0.03856841,  0.04281293],
       [-0.01409448,  0.00152295, -0.0401078 ,  0.02151066, -0.02573876,
         0.03013865, -0.00471014, -0.01068258, -0.02545031,  0.00162345],
       [ 0.04024539, -0.03094944, -0.01136745,  0.04316707,  0.03758668,
         0.00024635, -0.02356311,  0.04870843